name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version  (ie 1.1.1)'
        required: true

jobs:        
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name malykhin
          git config user.email malykhin@ukr.net
          git remote remove origin
          git remote add origin https://${{ secrets.TEST_RECORDER_ACCESS_KEY }}@github.com/roboportal/dakka.git
      - run: npm version ${{ github.event.inputs.version }}
      - run: git push origin master
      - run: |
          git checkout -b release/v${{ github.event.inputs.version }}
          git push origin release/v${{ github.event.inputs.version }}


